name: Deploy no vercel

on:
  push:
    branches:
      - imsi-action

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment (with Org/Project)
        if: ${{ secrets.VERCEL_ORG_ID && secrets.VERCEL_PROJECT_ID }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment (default)
        if: ${{ ! (secrets.VERCEL_ORG_ID && secrets.VERCEL_PROJECT_ID) }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Artifacts (with Org/Project)
        if: ${{ secrets.VERCEL_ORG_ID && secrets.VERCEL_PROJECT_ID }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Artifacts (default)
        if: ${{ ! (secrets.VERCEL_ORG_ID && secrets.VERCEL_PROJECT_ID) }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (with Org/Project)
        if: ${{ secrets.VERCEL_ORG_ID && secrets.VERCEL_PROJECT_ID }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (default)
        if: ${{ ! (secrets.VERCEL_ORG_ID && secrets.VERCEL_PROJECT_ID) }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}